"""Add missing fields to Exam, Question, Submission, Answer, Subject, Level models

Revision ID: 03efd9b53b39
Revises: de27dde3aa17
Create Date: 2026-02-10 08:20:18.979526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03efd9b53b39'
down_revision = 'de27dde3aa17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answer', sa.Text(), nullable=True))
        batch_op.drop_column('student_answer')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('pass_score', sa.Float(), nullable=False, server_default='60.0'))

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.drop_column('text')
        batch_op.drop_column('order_num')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('obtained_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_passed', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_column('is_passed')
        batch_op.drop_column('score_percentage')
        batch_op.drop_column('obtained_score')
        batch_op.drop_column('status')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('order_index')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_num', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.drop_column('explanation')
        batch_op.drop_column('order_index')
        batch_op.drop_column('content')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('order_index')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('pass_score')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('is_active')
        batch_op.drop_column('description')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_answer', sa.TEXT(), nullable=True))
        batch_op.drop_column('user_answer')

    # ### end Alembic commands ###
