"""Add is_temporary field to Exam model

Revision ID: 5f43d8aa9fe7
Revises: 6480e0844716
Create Date: 2026-02-27 15:18:55.415776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f43d8aa9fe7'
down_revision = '6480e0844716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可为NULL的列
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=True))

    # 为现有记录设置默认值
    op.execute("UPDATE exams SET is_temporary = 0")

    # 修改列为NOT NULL
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('is_temporary', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')
    # ### end Alembic commands ###
