"""Add question_ids field to Submission model for practice mode

Revision ID: c2d7e7e80cad
Revises: 5f43d8aa9fe7
Create Date: 2026-02-27 15:34:58.662957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d7e7e80cad'
down_revision = '5f43d8aa9fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('question_ids')

    # ### end Alembic commands ###
