"""Make Question.exam_id nullable

Revision ID: f3eed5b46a1a
Revises: c2d7e7e80cad
Create Date: 2026-02-28 11:48:12.007688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f3eed5b46a1a'
down_revision = 'c2d7e7e80cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_bind_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_bind_requests_student_id')
        batch_op.drop_index('ix_teacher_bind_requests_teacher_id')

    op.drop_table('teacher_bind_requests')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('question_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_ids', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.BOOLEAN(), nullable=False))

    op.create_table('teacher_bind_requests',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_bind_requests', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_bind_requests_teacher_id', ['teacher_id'], unique=False)
        batch_op.create_index('ix_teacher_bind_requests_student_id', ['student_id'], unique=False)

    # ### end Alembic commands ###
